

<?php

// Assuming you have a database connection established (e.g., $db)
// This example uses a simplified database for demonstration.  
// In a real application, you'll likely use a proper database library and 
// sanitize and validate user input thoroughly.

// Example database credentials (replace with your actual credentials)
$db_host = "localhost";
$db_name = "your_database_name";
$db_user = "your_username";
$db_password = "your_password";

/**
 * Resets a user's password.
 *
 * @param string $email The user's email address.
 * @return string A message indicating the success or failure of the operation.
 */
function forgotPassword(string $email): string
{
    // 1. Validate Input (Essential for security)
    if (empty($email)) {
        return "Error: Email address is required.";
    }

    // In a real application, you'd likely verify that the email exists in your system.
    // This is a simplified example that assumes the email exists.

    // 2. Generate a Unique Token (for security)
    $token = bin2hex(random_bytes(32)); // Use random_bytes for security

    // 3. Create a Reset Token Record (Simulated Database Operation)
    // In a real implementation, you'd use a database query.
    // This simulates creating a record in a table like 'reset_tokens'.
    // This table should have columns like: id, email, token, expiry_time
    $reset_token = [
        'id' => 1, // Unique ID (generated by your system)
        'email' => $email,
        'token' => $token,
        'expiry_time' => time() + 3600 // Expires in 1 hour
    ];

    // 4. Send an Email with a Reset Link
    $to = $email;
    $subject = "Password Reset Request";
    $message = "Please click the following link to reset your password: " . $_SERVER['REQUEST_SCHEME'] . "://yourdomain.com/reset_password?token=" . $token;
    $headers = "From: your_email@example.com";

    mail($to, $message, $headers); 

    return "Password reset link has been sent to your email address.";
}


// Example Usage:
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $email = $_POST["email"];  // Get email from form

    if (filter_input(INPUT_POST, "email", FILTER_SANITIZE_EMAIL)) { //Sanitize input - VERY IMPORTANT!
        $result = forgotPassword($email);
        echo $result;
    } else {
        echo "Invalid email format.";
    }
}
?>
