

<?php

/**
 * User Review Function
 *
 * This function allows users to submit and display reviews.
 *
 * @param string $productId The ID of the product being reviewed.
 * @param string $reviewerName The name of the reviewer.
 * @param string $reviewText The review text.
 * @param int $rating (Optional) A rating from 1 to 5. Defaults to 0.
 *
 * @return array An array containing the review data (success/failure message, review data if successful)
 */
function submitReview(string $productId, string $reviewerName, string $reviewText, int $rating = 0) {
  // Input validation - add more robust validation as needed for production
  if (empty($productId)) {
    return array('success' => false, 'message' => 'Product ID cannot be empty.');
  }
  if (empty($reviewerName)) {
    return array('success' => false, 'message' => 'Reviewer Name cannot be empty.');
  }
  if (empty($reviewText)) {
    return array('success' => false, 'message' => 'Review Text cannot be empty.');
  }

  // Validate the rating
  if ($rating < 1 || $rating > 5) {
    return array('success' => false, 'message' => 'Rating must be between 1 and 5.');
  }


  //  Here you would typically save the review data to a database.
  //  This is a placeholder for demonstration.

  $reviewData = array(
    'productId' => $productId,
    'reviewerName' => $reviewerName,
    'reviewText' => $reviewText,
    'rating' => $rating,
    'submissionTime' => date('Y-m-d H:i:s')  // Add timestamp
  );

  //  For demonstration, we'll just store the review data in an array.
  //  In a real application, you would save this to a database.

  //  Simulate saving to a database (replace this with actual database code)
  //  $db = new DatabaseConnection(); // Assuming you have a database connection class
  //  $db->insertReview($reviewData);

  return array('success' => true, 'reviewData' => $reviewData);
}


/**
 * Display Reviews - Example Function
 *
 *  This is an example function to display reviews.
 *
 * @param array $reviews  An array of reviews (returned by submitReview).
 */
function displayReviews(array $reviews) {
  echo "<h2>Reviews for Product ID: " . $reviews[0]['productId'] . "</h2>";  // Display the product ID

  if (empty($reviews)) {
    echo "<p>No reviews yet.</p>";
    return;
  }

  echo "<ul>";
  foreach ($reviews as $review) {
    echo "<li>";
    echo "<strong>" . $review['reviewerName'] . ":</strong> " . $review['reviewText'] . " (Rating: " . $review['rating'] . ") - " . $review['submissionTime'] . "</li>";
  }
  echo "</ul>";
}


// Example Usage:
$productID = "P123";

// Submit a review
$reviewResult = submitReview($productID, "John Doe", "Great product!  I love it!", 5);

if ($reviewResult['success']) {
  echo "<p>Review submitted successfully!</p>";
  $reviewData = $reviewResult['reviewData'];
  echo "<p>Review ID: " . $reviewData['reviewId'] . " (Generated by system)</p>";
  displayReviews([$reviewData]); // Pass the review data to displayReviews
} else {
  echo "<p>Error submitting review: " . $reviewResult['message'] . "</p>";
}


// Example of submitting an invalid review:
$invalidReviewResult = submitReview("", "Jane Smith", "Terrible!", 1);

if (!$invalidReviewResult['success']) {
    echo "<p>Invalid Review Submission Result: " . $invalidReviewResult['message'] . "</p>";
}
?>
